framework:
<<<<<<< HEAD
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
=======
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
>>>>>>> c014c8c2a5ddff0a54800e95aa480d439d3ee775
