<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJT6U0jJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJT6U0jJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJT6U0jJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJT6U0jJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJT6U0jJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'JT6U0jJ',
    'container.build_id' => 'ecc1ff20',
    'container.build_time' => 1586534291,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJT6U0jJ');
