<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOtZmsrm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOtZmsrm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOtZmsrm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOtZmsrm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOtZmsrm\App_KernelDevDebugContainer([
    'container.build_hash' => 'OtZmsrm',
    'container.build_id' => 'c7f718ab',
    'container.build_time' => 1586260135,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOtZmsrm');
