<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKbtppz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKbtppz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNKbtppz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNKbtppz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNKbtppz\App_KernelDevDebugContainer([
    'container.build_hash' => 'NKbtppz',
    'container.build_id' => '79e58353',
    'container.build_time' => 1586482857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKbtppz');
