<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEs5qpch\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEs5qpch/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEs5qpch.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEs5qpch\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEs5qpch\App_KernelDevDebugContainer([
    'container.build_hash' => 'Es5qpch',
    'container.build_id' => 'f678fca6',
    'container.build_time' => 1585831103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEs5qpch');
