<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAjTjkcx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAjTjkcx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAjTjkcx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAjTjkcx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAjTjkcx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AjTjkcx',
    'container.build_id' => '4a27ca73',
    'container.build_time' => 1586153996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAjTjkcx');
