<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBBttx7h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBBttx7h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBBttx7h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBBttx7h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBBttx7h\App_KernelDevDebugContainer([
    'container.build_hash' => 'BBttx7h',
    'container.build_id' => '1983e90e',
    'container.build_time' => 1585742771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBBttx7h');
