#index:
#    path: /
#    controller: App\Controller\DefaultController::index
<<<<<<< HEAD
=======
home:
  path: /
  controller: App\Controller\HomeController::index
>>>>>>> c014c8c2a5ddff0a54800e95aa480d439d3ee775
